version: '3.8'

services:
  frontend:
    build:
      context: ./app/frontend
    container_name: frontend
    ports:
      - "80:80"  # Expose frontend on port 80
    depends_on:
      - backend  # Ensure the backend starts before the frontend
    networks:
      - app-network  # Attach to a shared network

  backend:
    build:
      context: ./app/backend
    container_name: backend
    expose:
      - "5000"  # Expose port 5000 to NGINX
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
    depends_on:
      - db  # Ensure the backend waits for the DB to be ready
    networks:
      - app-network  # Attach to the shared network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom NGINX config
      - ./app/frontend/build:/usr/share/nginx/html  # Mount React build directory
    ports:
      - "80:80"  # Expose port 80 for the frontend and proxy
    depends_on:
      - frontend
      - backend  # NGINX depends on frontend and backend services
    networks:
      - app-network  # Attach to the shared network

networks:
  app-network:
    driver: bridge  # Create a custom network for frontend, backend, and nginx
