version: '1'


networks:
  Nancy_network:
    external: true

services:      
  stockdatabase:
    image: userDB
    ports:
      - 6000:6000
    networks:
      - Nancy_network

  signIndatabase:
    image: signInDB
    ports:
      - 7000:7000
    networks:
      - Nancy_network