version: '3.9'


networks:
  Nancy_network:
    external: true

services:      
  stockdatabase:
    image: stockdb
    ports:
      - 6000:6000
    networks:
      - Nancy_network

  signindatabase:
    image: signdb
    ports:
      - 7000:7000
    networks:
      - Nancy_network