version: '3.8'

services:
  flask-app:
    build: .
    container_name: userDB
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: always
